name: Self-hosted Nix Setup
description: Sets up Nix on a containerized self-hosted runner
inputs:
  shell:
    description: "Shell to use"
    required: true
    default: "bash"
runs:
  using: "composite"
  steps:
    - name: Self-hosted Runner Dependencies & Info
      shell: ${{ inputs.shell }}
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl build-essential
        ARCH="$(uname -m)"
        if [ "$ARCH" == "x86_64" ]; then
          ARCH="amd64"
        fi
        curl -LO "https://github.com/fastfetch-cli/fastfetch/releases/download/2.20.0/fastfetch-linux-${ARCH}.deb"
        sudo dpkg -i "fastfetch-linux-${ARCH}.deb"
        fastfetch
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        init: none
        extra-conf: |
          sandbox = false
    - name: Change user for single-user installation of Nix
      shell: ${{ inputs.shell }}
      run: |
        sudo chown --recursive "runner" /nix
